<?php

/**
 * @file
 * Contains module hooks.
 */

/**
 * Implements hook_theme().
 */
function hm_newsletter_theme($existing, $type, $theme, $path) {
  return [
    'hm_newsletter_form' => [
      'variables' => [
        'newsletters' => NULL,
        'client_id' => '',
        'birthday' => [],
        'imprint_text' => '',
        'title' => 1,
        'firstname' => 1,
        'name' => 1,
        'zipcode' => 1,
        'location' => 1,
        'birthdate' => 1,
        'headline' => '',
        'text' => '',
        'confirmation_headline' => '',
        'confirmation_text' => '',
        'source' => '',
        'privacy' => '',
        'optin' => '',
        'submit_label' => '',
        'email' => '',
      ],
    ],
  ];
}
