hm_newsletter.settings:
  type: config_object
  label: 'Harbourmaster newsletter settings'
  mapping:
    hm_environment:
      type: string
      label: 'Environment'
    hm_client_id:
      type: string
      label: 'Client ID'
    hm_imprint_text:
      type: string
      label: 'Imprint text'
    hm_displayed_agreements:
      type: sequence
      label: 'List of displayed agreements'
      sequence:
        type: string
        label: 'Agreement index'
